version: "3"

services:
  nginx_app:
    image: nginx:latest
    depends_on:
      - flask_app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - my_project_network

  flask_app:
    build: .
    volumes:
      - .:/my_project
    command: python3 /my_project/index.py
    networks:
      - my_project_network
  
networks:
  my_project_network:

